name = "guestbook-worker"
main = "src/index.js"
compatibility_date = "2024-05-01"

# Variables accessible in the Worker script
[vars]
NOTION_VERSION = "2022-06-28"

# Secrets (set these using `wrangler secret put`)
# NOTION_SECRET = "..."  # Your Notion integration token
# NOTION_DB = "..."      # Your Notion database ID

# KV namespace for rate limiting (optional, uncomment and configure if needed)
# [[kv_namespaces]]
# binding = "RATE_KV"
# id = "your-kv-namespace-id"
# preview_id = "your-kv-preview-id"
